//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BP.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área Administrativa.
        /// </summary>
        public static string Admin_AreaAdministrador {
            get {
                return ResourceManager.GetString("Admin_AreaAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string Admin_CRUD_Livro_Autor {
            get {
                return ResourceManager.GetString("Admin_CRUD_Livro_Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero.
        /// </summary>
        public static string Admin_CRUD_Livro_Genero {
            get {
                return ResourceManager.GetString("Admin_CRUD_Livro_Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de Livros Disponível.
        /// </summary>
        public static string Admin_CRUD_Livro_QuantidadeDisponivel {
            get {
                return ResourceManager.GetString("Admin_CRUD_Livro_QuantidadeDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinópse.
        /// </summary>
        public static string Admin_CRUD_Livro_Sinopse {
            get {
                return ResourceManager.GetString("Admin_CRUD_Livro_Sinopse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título do Livro.
        /// </summary>
        public static string Admin_CRUD_Livro_TituloLivro {
            get {
                return ResourceManager.GetString("Admin_CRUD_Livro_TituloLivro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Diária.
        /// </summary>
        public static string Admin_CRUD_Livro_ValorDia {
            get {
                return ResourceManager.GetString("Admin_CRUD_Livro_ValorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Novo Livro.
        /// </summary>
        public static string Admin_Livro_CadastrarNovoLivro {
            get {
                return ResourceManager.GetString("Admin_Livro_CadastrarNovoLivro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Livro.
        /// </summary>
        public static string Admin_Livro_DadosLivro {
            get {
                return ResourceManager.GetString("Admin_Livro_DadosLivro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Livro {0}.
        /// </summary>
        public static string Admin_Livro_EditarLivro {
            get {
                return ResourceManager.GetString("Admin_Livro_EditarLivro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parabéns! Você realizou o aluguel dos livros abaixo com Sucesso!&lt;br/&gt; Fique atento em relação ao prazo de entrega. &lt;br/&gt; Para realizar a entrega dos livros, pode ser feita a postagem via Correios ou  a entrega pode ser feita pessoalmente. Para maiores informações ligue para o número (31) 4444-0044.
        /// </summary>
        public static string Aluguel_AluguelEfetuadoComSucesso {
            get {
                return ResourceManager.GetString("Aluguel_AluguelEfetuadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Aluguel.
        /// </summary>
        public static string Aluguel_DadosDoAluguel {
            get {
                return ResourceManager.GetString("Aluguel_DadosDoAluguel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Vencimento da Devolução.
        /// </summary>
        public static string Aluguel_DataParaDevolucao {
            get {
                return ResourceManager.GetString("Aluguel_DataParaDevolucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data prevista para entrega pelos Correios.
        /// </summary>
        public static string Aluguel_DataPrevistaEntrega {
            get {
                return ResourceManager.GetString("Aluguel_DataPrevistaEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente alugar todos os livros que estão em seu carrinho?.
        /// </summary>
        public static string Aluguel_DesejaAlugar {
            get {
                return ResourceManager.GetString("Aluguel_DesejaAlugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efetuar aluguel dos livros do Carrinho.
        /// </summary>
        public static string Aluguel_EfetuarAluguel {
            get {
                return ResourceManager.GetString("Aluguel_EfetuarAluguel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum livro selecionado para o aluguel..
        /// </summary>
        public static string Aluguel_NenhumLivroSelecionado {
            get {
                return ResourceManager.GetString("Aluguel_NenhumLivroSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Aluguel.
        /// </summary>
        public static string Aluguel_ValorAluguel {
            get {
                return ResourceManager.GetString("Aluguel_ValorAluguel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Frete.
        /// </summary>
        public static string Aluguel_ValorFrete {
            get {
                return ResourceManager.GetString("Aluguel_ValorFrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string Btn_Confirmar {
            get {
                return ResourceManager.GetString("Btn_Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Btn_Salvar {
            get {
                return ResourceManager.GetString("Btn_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar-se no Sistema.
        /// </summary>
        public static string CadastrarUsuario_Titulo {
            get {
                return ResourceManager.GetString("CadastrarUsuario_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar ao Carrinho.
        /// </summary>
        public static string Carrinho_Adicionar {
            get {
                return ResourceManager.GetString("Carrinho_Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do livro inválido..
        /// </summary>
        public static string Carrinho_CodigoLivroInvalido {
            get {
                return ResourceManager.GetString("Carrinho_CodigoLivroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar adicionar livro ao carrinho..
        /// </summary>
        public static string Carrinho_ErroAoAdicionarLivro {
            get {
                return ResourceManager.GetString("Carrinho_ErroAoAdicionarLivro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has not registered cart..
        /// </summary>
        public static string Carrinho_Inexistente {
            get {
                return ResourceManager.GetString("Carrinho_Inexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livro adicionado ao carrinho com sucesso!.
        /// </summary>
        public static string Carrinho_LivroAdicionadoComSucesso {
            get {
                return ResourceManager.GetString("Carrinho_LivroAdicionadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este livro já foi adicionado ao seu carrinho de compras..
        /// </summary>
        public static string Carrinho_LivroJaAdicionado {
            get {
                return ResourceManager.GetString("Carrinho_LivroJaAdicionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livro não está disponível para aluguel..
        /// </summary>
        public static string Carrinho_LivroNaoDisponivel {
            get {
                return ResourceManager.GetString("Carrinho_LivroNaoDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livro Removido do Carrinho com Sucesso.
        /// </summary>
        public static string Carrinho_LivroRemovidoComSucesso {
            get {
                return ResourceManager.GetString("Carrinho_LivroRemovidoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meu Carrinho.
        /// </summary>
        public static string Carrinho_MeuCarrinho {
            get {
                return ResourceManager.GetString("Carrinho_MeuCarrinho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Livro do Carrinho.
        /// </summary>
        public static string Carrinho_RemoverLivro {
            get {
                return ResourceManager.GetString("Carrinho_RemoverLivro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string CRUD_Usuario_Bairro {
            get {
                return ResourceManager.GetString("CRUD_Usuario_Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string CRUD_Usuario_CEP {
            get {
                return ResourceManager.GetString("CRUD_Usuario_CEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string CRUD_Usuario_Cidade {
            get {
                return ResourceManager.GetString("CRUD_Usuario_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string CRUD_Usuario_DataNascimento {
            get {
                return ResourceManager.GetString("CRUD_Usuario_DataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string CRUD_Usuario_Estado {
            get {
                return ResourceManager.GetString("CRUD_Usuario_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login já utilizado..
        /// </summary>
        public static string CRUD_Usuario_LoginJaUtilizado {
            get {
                return ResourceManager.GetString("CRUD_Usuario_LoginJaUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        public static string CRUD_Usuario_Logradouro {
            get {
                return ResourceManager.GetString("CRUD_Usuario_Logradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string CRUD_Usuario_Nome {
            get {
                return ResourceManager.GetString("CRUD_Usuario_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string CRUD_Usuario_NumeroEndereco {
            get {
                return ResourceManager.GetString("CRUD_Usuario_NumeroEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string CRUD_Usuario_Senha {
            get {
                return ResourceManager.GetString("CRUD_Usuario_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string CRUD_Usuario_Telefone {
            get {
                return ResourceManager.GetString("CRUD_Usuario_Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar minha senha para meu e-mail.
        /// </summary>
        public static string EsqueciMinhaSenha_EnviarMinhaSenha {
            get {
                return ResourceManager.GetString("EsqueciMinhaSenha_EnviarMinhaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha foi enviada ao e-mail cadastrado no site com sucesso!.
        /// </summary>
        public static string EsqueciMinhaSenha_SenhaEnviadaComSucesso {
            get {
                return ResourceManager.GetString("EsqueciMinhaSenha_SenhaEnviadaComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário informado não existe..
        /// </summary>
        public static string EsqueciMinhaSenha_UsuarioInexistente {
            get {
                return ResourceManager.GetString("EsqueciMinhaSenha_UsuarioInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Link_Editar {
            get {
                return ResourceManager.GetString("Link_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Link_Excluir {
            get {
                return ResourceManager.GetString("Link_Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string Link_Novo {
            get {
                return ResourceManager.GetString("Link_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar para Lista.
        /// </summary>
        public static string Link_VoltarParaLista {
            get {
                return ResourceManager.GetString("Link_VoltarParaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não autorizado.
        /// </summary>
        public static string Login_AcessoNaoAutorizado {
            get {
                return ResourceManager.GetString("Login_AcessoNaoAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        public static string Login_Cadastrar {
            get {
                return ResourceManager.GetString("Login_Cadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Login_Entrar {
            get {
                return ResourceManager.GetString("Login_Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar no Sistema.
        /// </summary>
        public static string Login_EntrarNoSistema {
            get {
                return ResourceManager.GetString("Login_EntrarNoSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci minha senha.
        /// </summary>
        public static string Login_EsqueciMinhaSenha {
            get {
                return ResourceManager.GetString("Login_EsqueciMinhaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha:.
        /// </summary>
        public static string Login_Senha {
            get {
                return ResourceManager.GetString("Login_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário:.
        /// </summary>
        public static string Login_Usuario {
            get {
                return ResourceManager.GetString("Login_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválidos.
        /// </summary>
        public static string Login_UsuarioOuSenhaInvalidos {
            get {
                return ResourceManager.GetString("Login_UsuarioOuSenhaInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não possui acesso à esta área do site..
        /// </summary>
        public static string Login_VoceNaoPossuiPermissao {
            get {
                return ResourceManager.GetString("Login_VoceNaoPossuiPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar à página inicial.
        /// </summary>
        public static string Login_VoltarPaginaInicial {
            get {
                return ResourceManager.GetString("Login_VoltarPaginaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá {0}.
        /// </summary>
        public static string MenuPrincipal_BoasVindas {
            get {
                return ResourceManager.GetString("MenuPrincipal_BoasVindas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clássico.
        /// </summary>
        public static string MenuPrincipal_Classico {
            get {
                return ResourceManager.GetString("MenuPrincipal_Classico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        public static string MenuPrincipal_Drama {
            get {
                return ResourceManager.GetString("MenuPrincipal_Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Empréstimos.
        /// </summary>
        public static string MenuPrincipal_Emprestimos {
            get {
                return ResourceManager.GetString("MenuPrincipal_Emprestimos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página Inicial.
        /// </summary>
        public static string MenuPrincipal_HomePage {
            get {
                return ResourceManager.GetString("MenuPrincipal_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livros.
        /// </summary>
        public static string MenuPrincipal_Livros {
            get {
                return ResourceManager.GetString("MenuPrincipal_Livros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros.
        /// </summary>
        public static string MenuPrincipal_Outros {
            get {
                return ResourceManager.GetString("MenuPrincipal_Outros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retornar ao Site.
        /// </summary>
        public static string MenuPrincipal_RetornarAoSite {
            get {
                return ResourceManager.GetString("MenuPrincipal_RetornarAoSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance.
        /// </summary>
        public static string MenuPrincipal_Romance {
            get {
                return ResourceManager.GetString("MenuPrincipal_Romance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vazar.
        /// </summary>
        public static string MenuPrincipal_Sair {
            get {
                return ResourceManager.GetString("MenuPrincipal_Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione seu idioma:.
        /// </summary>
        public static string MenuPrincipal_SelecionarIdioma {
            get {
                return ResourceManager.GetString("MenuPrincipal_SelecionarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terror.
        /// </summary>
        public static string MenuPrincipal_Terror {
            get {
                return ResourceManager.GetString("MenuPrincipal_Terror", resourceCulture);
            }
        }
    }
}
